--- 
- 
  become: true
  hosts: node1
  name: "NTP Server Configuration"
  tasks: 
    - 
      name: "Install latest package of firewalld"
      yum: 
        name: firewalld
        state: latest
    - 
      name: "Start & Enable the firewalld service"
      service: 
        enabled: true
        name: firewalld
        state: started
    - 
      name: "configure ntp server/client using chrony"
      shell: "firewall-cmd --add-service=ntp --permanent"
    - 
      name: "firewall reload"
      shell: "firewall-cmd --reload"
    - 
      name: "Make sure Chrony is started up"
      service: "name=chronyd state=started enabled=yes"
      tags: chrony
    - 
      name: "Install NTP"
      tags: ntp
      yum: "name=ntp state=installed"
    - 
      copy: "src=/etc/chrony.conf dest=/etc/chrony.conf"
      name: "Copy over the NTP configuration"
      notify: 
        - "restart ntpd"
      tags: ntp
    - 
      name: "Make sure NTP is started up"
      service: "name=ntpd state=restarted enabled=yes"
      tags: ntp
